import test from 'node:test';
import assert from 'node:assert/strict';
import { createCameraCapture } from '../app/camera-capture.ts';
import { attachVideoPlayback } from '../app/video-playback.ts';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}};
class Track extends EventTarget {readyState='live'; muted=false; stop(){this.readyState='ended';}}
class Stream extends EventTarget {constructor(){super();this.track=new Track();}getVideoTracks(){return [this.track];}getTracks(){return [this.track];}}
function camera(){const requests=[],changes=[],released=[],errors=[];const ctl=createCameraCapture({capture:()=>{const p=deferred();requests.push(p);return p.promise;},publish:async()=>{},release:s=>released.push(s),changed:s=>changes.push(s),error:e=>errors.push(e)});return {ctl,requests,changes,released,errors};}
test('concurrent camera starts acquire once; cancelled permission response never becomes a camera',async()=>{const s=camera(),p=s.ctl.start();await s.ctl.start();assert.equal(s.requests.length,1);s.ctl.stop();await s.ctl.start();assert.equal(s.requests.length,1);const stream=new Stream();s.requests[0].resolve(stream);await p;assert.equal(stream.track.readyState,'ended');assert.deepEqual(s.changes,[null]);assert.equal(s.errors.length,0);});
test('late ended from an old camera cannot clear the new camera',async()=>{const s=camera(),a=new Stream(),b=new Stream();const first=s.ctl.start();s.requests[0].resolve(a);await first;s.ctl.stop();const next=s.ctl.start();s.requests[1].resolve(b);await next;a.track.dispatchEvent(new Event('ended'));assert.equal(s.changes.at(-1),b);b.track.readyState='ended';b.track.dispatchEvent(new Event('ended'));assert.equal(s.changes.at(-1),null);});
test('publish failure releases capture and permits retry',async()=>{const media=new Stream(),errors=[];const c=createCameraCapture({capture:async()=>media,publish:async()=>{throw Error('publish failed')},release:()=>{},changed:()=>{},error:e=>errors.push(e)});await c.start();assert.equal(media.track.readyState,'ended');assert.equal(errors.length,1);});
test('camera stopped during publishing cannot be resurrected by its late completion',async()=>{const media=new Stream(),publish=deferred(),changes=[];const c=createCameraCapture({capture:async()=>media,publish:()=>publish.promise,release:()=>{},changed:s=>changes.push(s),error:()=>{}});const p=c.start();await Promise.resolve();c.stop();publish.resolve();await p;assert.deepEqual(changes,[null]);assert.equal(media.track.readyState,'ended');});
class Video extends EventTarget {paused=true; readyState=0; calls=0;reject=false;play(){this.calls++;if(this.reject)return Promise.reject(new DOMException('blocked','NotAllowedError'));this.paused=false;return Promise.resolve();}pause(){this.paused=true;}}
const tick=()=>new Promise(r=>setImmediate(r));
test('video resumes after capture unmute and foreground, with Safari inline attributes',async()=>{const video=new Video(),stream=new Stream(),doc=new EventTarget(),win=new EventTarget(),blocked=[];doc.visibilityState='visible';stream.track.muted=true;const p=attachVideoPlayback(video,stream,{document:doc,window:win,blocked:b=>blocked.push(b)});assert.equal(video.calls,0);assert.equal(video.playsInline,true);assert.equal(video.muted,true);stream.track.muted=false;stream.track.dispatchEvent(new Event('unmute'));await tick();assert.equal(video.paused,false);doc.visibilityState='hidden';doc.dispatchEvent(new Event('visibilitychange'));const calls=video.calls;assert.equal(video.calls,calls);doc.visibilityState='visible';doc.dispatchEvent(new Event('visibilitychange'));await new Promise(r=>setTimeout(r,300));assert.ok(video.calls>calls);p.dispose();const end=video.calls;stream.track.dispatchEvent(new Event('unmute'));win.dispatchEvent(new Event('pageshow'));assert.equal(video.calls,end);assert.equal(video.srcObject,null);assert.equal(stream.track.readyState,'live');});
test('autoplay failure exposes retry and an interaction recovers playback',async()=>{const video=new Video(),stream=new Stream(),doc=new EventTarget(),win=new EventTarget(),blocked=[];doc.visibilityState='visible';video.reject=true;const p=attachVideoPlayback(video,stream,{document:doc,window:win,blocked:b=>blocked.push(b)});await tick();assert.equal(blocked.at(-1),true);video.reject=false;doc.dispatchEvent(new Event('pointerup'));await tick();assert.equal(blocked.at(-1),false);p.dispose();});
