import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { createHmac, randomUUID } from 'node:crypto';
import { createServer } from 'node:net';
import { encryptToken } from '../app/api/ticktick/crypto.ts';
import { taskFields } from '../app/api/room/tasks/store.ts';

test('claim workflow HTTP covers actual routes, sidebar guard, file streaming, role checks and approval', { timeout: 40000 }, async () => {
  await mkdir('codex-generated/test-data', { recursive: true });
  const dir = await mkdtemp(path.resolve('codex-generated/test-data/workflow-http-'));
  const secret = randomUUID(), previous = process.env.TICKTICK_STORAGE_SECRET;
  process.env.TICKTICK_STORAGE_SECRET = secret;
  const users = Object.fromEntries(['alice', 'bob'].map(id => [id, { nickname: id, ticktickToken: encryptToken('fixture-' + id) }]));
  if (previous === undefined) delete process.env.TICKTICK_STORAGE_SECRET; else process.env.TICKTICK_STORAGE_SECRET = previous;
  await writeFile(path.join(dir, 'identities.json'), JSON.stringify({ version: 1, users }));
  await mkdir(path.join(dir, 'cloud-drive', 'tasks', 'test'), { recursive: true });
  await writeFile(path.join(dir, 'cloud-drive', 'tasks', 'test', 'test.pdf'), 'fixture attachment');
  await writeFile(path.join(dir, 'fake-dida.json'), JSON.stringify({ alice: { original: { id: 'original', projectId: 'inbox-alice', ...taskFields({ title: 'HTTP 认领测试' }) } }, bob: {} }));
  const socket = createServer(); await new Promise(resolve => socket.listen(0, '127.0.0.1', resolve)); const port = socket.address().port; await new Promise(resolve => socket.close(resolve));
  const child = spawn(process.execPath, ['--import', './tests/helpers/dida-fixture.mjs', 'node_modules/next/dist/bin/next', 'start', '--hostname', '127.0.0.1', '--port', String(port)], { env: { ...process.env, DATA_DIR: dir, AUTH_SESSION_SECRET: secret, TICKTICK_STORAGE_SECRET: secret, SITE_PASSWORD: 'fixture', IDENTITY_CODE_HASHES: '', VAPID_PUBLIC_KEY: '', VAPID_PRIVATE_KEY: '' }, stdio: 'ignore', windowsHide: true });
  const origin = `http://127.0.0.1:${port}`;
  const cookie = id => { const payload = `${id}.${Math.floor(Date.now() / 1000) + 600}`; return `ss_access=${payload}.${createHmac('sha256', secret).update(payload).digest('base64url')}`; };
  const call = (id, route = '/api/room/tasks', body, headers = {}) => fetch(origin + route, { method: body === undefined ? 'GET' : 'POST', redirect: 'manual', headers: { Cookie: cookie(id), Origin: origin, 'Content-Type': 'application/json', ...headers }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  try {
    let ready = false; for (let i = 0; i < 60; i++) { try { if ((await fetch(origin + '/access')).ok) { ready = true; break; } } catch {} await new Promise(resolve => setTimeout(resolve, 200)); } assert.ok(ready);
    const login = (code, next, json = true) => fetch(origin + '/api/access', { method:'POST',redirect:'manual',headers:json?{Accept:'application/json'}:{},body:new URLSearchParams({identityCode:code,next}) });
    let loginResponse=await login('wrong','/');assert.equal(loginResponse.status,401);assert.ok(!loginResponse.headers.has('set-cookie'));
    loginResponse=await login('fixture','/?view=tasks');assert.equal(loginResponse.status,200);assert.deepEqual(await loginResponse.json(),{next:'/?view=tasks',displayName:'legacy'});assert.match(loginResponse.headers.get('set-cookie'),/HttpOnly/);assert.match(loginResponse.headers.get('set-cookie'),/Secure/);
    assert.equal((await call('legacy','/api/room/classroom')).status,200,'first login creates a usable room profile before entry');
    assert.equal((await call('legacy','/api/room/boards')).status,200);
    const profiles = JSON.parse(await readFile(path.join(dir, 'identities.json'), 'utf8'));
    profiles.users.legacy.nickname = '测试昵称';
    await writeFile(path.join(dir, 'identities.json'), JSON.stringify(profiles));
    loginResponse=await login('fixture','https://outside.example');assert.deepEqual(await loginResponse.json(),{next:'/',displayName:'测试昵称'});
    assert.equal((await (await call('legacy','/api/identity/me')).json()).nickname, '测试昵称');
    loginResponse=await login('fixture','/api/ticktick/diagnostics',false);assert.equal(loginResponse.status,303);assert.equal(loginResponse.headers.get('location'),'/api/ticktick/diagnostics');
    loginResponse=await login('wrong','/',false);assert.equal(loginResponse.status,303);assert.match(loginResponse.headers.get('location'),/error=1/);
    const boardId=randomUUID();assert.equal((await call('alice','/api/room/boards',{id:''})).status,400);
    assert.equal((await call('alice','/api/room/boards',{id:boardId},{Origin:'https://elsewhere.example'})).status,403);
    assert.equal((await call('alice','/api/room/boards',{id:boardId})).status,200);
    assert.deepEqual((await (await call('bob','/api/room/boards')).json()).deletedBoardIds,[boardId]);
    assert.equal((await call('alice','/api/room/boards',{id:boardId})).status,200);
    const before = await (await call('alice')).json(), sourceTask = before.members.find(member => member.id === 'alice').tasks[0];
    const claim = { id: randomUUID(), action: 'claim', source: { ownerId: 'alice', taskId: sourceTask.id, version: sourceTask.version }, destination: 'bob' };
    let response = await call('bob', '/api/room/tasks', claim); assert.equal(response.status, 200); let w = (await response.json()).workflow; assert.equal(w.status, 'working');
    const arrangeCurrent = async () => {
      const snapshot = await (await call('bob', '/api/room/tasks?local=1')).json();
      const response = await call('bob', '/api/room/tasks', { id: randomUUID(), action: 'arrange-execution', version: snapshot.executionVersion, workflowIds: [w.id] });
      assert.equal(response.status, 200); w = (await response.json()).workflows.find(item => item.id === w.id);
    };
    assert.equal(w.executing, false);
    assert.equal((await call('bob', '/api/room/tasks', { id: randomUUID(), workflowId: w.id, version: w.version, action: 'submit' })).status, 409);
    await arrangeCurrent();
    const act = async (actor, action, extra = {}) => {
      if (actor === 'bob' && action === 'submit' && !w.executing) await arrangeCurrent();
      return call(actor, '/api/room/tasks', { id: randomUUID(), workflowId: w.id, version: w.version, action, ...extra });
    };
    assert.equal((await act('bob', 'nudge')).status, 403);
    response = await act('alice', 'nudge'); assert.equal(response.status, 200); w = (await response.json()).workflow;
    const nudge = w.events.find(event => event.type === 'nudge'); assert.ok(nudge);
    let notices = (await (await call('bob', '/api/room/tasks?revision=1')).json()).notices;
    const nudgeNotice = notices.find(item => item.eventId === nudge.id); assert.ok(nudgeNotice);
    response = await act('bob', 'reply-nudge', { replyTo: nudge.id, comment: '正在处理', version: 0 }); assert.equal(response.status, 200); w = (await response.json()).workflow;
    assert.equal(w.events.at(-1).replyTo, nudge.id);
    assert.equal((await call('bob', '/api/room/tasks', { action: 'read-notices', ids: [nudgeNotice.id] }, { Origin: 'https://foreign.example' })).status, 403);
    assert.equal((await call('bob', '/api/room/tasks', { action: 'read-notices', ids: [nudgeNotice.id] })).status, 200);
    notices = (await (await call('bob', '/api/room/tasks?revision=1')).json()).notices; assert.ok(!notices.some(item => item.id === nudgeNotice.id));
    assert.ok((await (await call('alice', '/api/room/tasks?revision=1')).json()).notices.some(item => item.eventType === 'reply-nudge'));
    response = await call('bob', '/api/ticktick/complete', { projectId: 'inbox-bob', taskId: w.targetId }); assert.equal(response.status, 403); assert.match((await response.json()).error, /审批/);
    response = await act('bob', 'update-workflow', { fields: { content: 'HTTP 修改详情\n[附件：测试.pdf](https://study.11scat.xyz/task-attachment?path=tasks%2Ftest%2Ftest.pdf)' } }); assert.equal(response.status, 200); w = (await response.json()).workflow;
    const edited = JSON.parse(await readFile(path.join(dir, 'fake-dida.json'), 'utf8')); assert.equal(edited.alice.original.content, 'HTTP 修改详情\n[附件：测试.pdf](https://study.11scat.xyz/task-attachment?path=tasks%2Ftest%2Ftest.pdf)'); assert.equal(edited.bob[w.targetId].content, 'HTTP 修改详情\n[附件：测试.pdf](https://study.11scat.xyz/task-attachment?path=tasks%2Ftest%2Ftest.pdf)');
    edited.bob[w.targetId].status = 2;
    await writeFile(path.join(dir, 'fake-dida.json'), JSON.stringify(edited));
    const externallyChecked = await (await call('bob')).json(); w = externallyChecked.workflows.find(item => item.id === w.id);
    assert.ok(!w.needsSubmission); assert.ok(!w.reopenPending);
    assert.equal(w.status, 'working'); assert.ok(!w.taskAnomaly, 'display does not infer deletion while completion synchronization is deferred');
    const upload = (actor, body, headers = {}) => fetch(`${origin}/api/room/tasks/files?workflow=${w.id}&name=${encodeURIComponent('评语.txt')}`, { method: 'POST', body, headers: { Cookie: cookie(actor), Origin: origin, ...headers }, redirect: 'manual' });
    assert.equal((await upload('alice', 'draft')).status, 403);
    assert.equal((await upload('bob', 'draft', { Origin: 'https://foreign.example' })).status, 403);
    assert.equal((await upload('unknown', 'draft')).status, 403);
    response = await upload('bob', '完成说明'); assert.equal(response.status, 200); const file = (await response.json()).file;
    assert.equal((await call('alice', file.url)).status, 403);
    const downloaded = await call('bob', file.url); assert.equal(downloaded.status, 200); assert.equal(await downloaded.text(), '完成说明'); assert.match(downloaded.headers.get('content-disposition'), /^attachment;/); assert.equal(downloaded.headers.get('x-content-type-options'), 'nosniff');
    const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jvWQAAAAASUVORK5CYII=', 'base64');
    response = await fetch(`${origin}/api/room/tasks/files?workflow=${w.id}&name=${encodeURIComponent('图1.png')}`, { method: 'POST', body: png, headers: { Cookie: cookie('bob'), Origin: origin } });
    assert.equal(response.status, 200); const imageFile = (await response.json()).file;
    assert.equal((await call('alice', imageFile.url + '?preview=1')).status, 403, 'unsubmitted images keep the existing access restriction');
    const preview = await call('bob', imageFile.url + '?preview=1');
    assert.equal(preview.status, 200); assert.equal(preview.headers.get('content-type'), 'image/png');
    assert.match(preview.headers.get('content-disposition'), /^inline;/); assert.match(preview.headers.get('content-security-policy'), /sandbox/);
    assert.deepEqual(Buffer.from(await preview.arrayBuffer()), png);
    assert.match((await call('bob', imageFile.url)).headers.get('content-disposition'), /^attachment;/);
    assert.match((await call('bob', file.url + '?preview=1')).headers.get('content-disposition'), /^attachment;/, 'non-image files retain download behavior');
    response = await act('bob', 'submit', { attachments: [file.id, imageFile.id], comment: '已完成 [图1.png]' }); assert.equal(response.status, 200); w = (await response.json()).workflow;
    assert.equal((JSON.parse(await readFile(path.join(dir, 'fake-dida.json'), 'utf8'))).bob[w.targetId].status, 0, 'dependent commands still verify and restore status before advancing');
    assert.equal((await call('alice', imageFile.url + '?preview=1')).status, 200, 'submitted images become visible to the reviewer');
    response = await act('alice', 'update-workflow', { fields: { content: '提交后补充任务说明和附件链接' } });
    assert.equal(response.status, 200); w = (await response.json()).workflow;
    assert.equal(w.status, 'submitted');
    assert.equal(w.events.filter(event => event.type === 'submit').length, 1);
    assert.ok(w.events.find(event => event.type === 'submit').files.some(item => item.id === file.id));
    const submittedExternal = JSON.parse(await readFile(path.join(dir, 'fake-dida.json'), 'utf8'));
    submittedExternal.bob[w.targetId].status = 2;
    await writeFile(path.join(dir, 'fake-dida.json'), JSON.stringify(submittedExternal));
    w = (await (await call('alice')).json()).workflows.find(item => item.id === w.id);
    assert.equal(w.status, 'submitted'); assert.ok(w.events.find(item => item.type === 'submit').files.some(item => item.id === file.id));
    assert.equal((await call('alice', file.url)).status, 200);
    assert.equal((await act('bob', 'approve')).status, 403);
    response = await upload('alice', '补充证明'); assert.equal(response.status, 200); const reviewFile = (await response.json()).file;
    response = await act('alice', 'reject', { attachments: [reviewFile.id], comment: '请补充证明' }); w = (await response.json()).workflow; assert.equal(w.status, 'rejected');
    assert.equal((await call('bob', reviewFile.url)).status, 200);
    const state = JSON.parse(await readFile(path.join(dir, 'fake-dida.json'), 'utf8')); assert.ok(!state.alice.original.status); assert.ok(!state.bob[w.targetId].status);
    const count = (await readdir(path.join(dir, 'workflow-files'))).length;
    response = await upload('bob', new Uint8Array(20 * 1024 * 1024 + 1)); assert.equal(response.status, 413); assert.equal((await readdir(path.join(dir, 'workflow-files'))).length, count);
    response = await act('bob', 'submit'); w = (await response.json()).workflow;
    const changedAfterSubmission = JSON.parse(await readFile(path.join(dir, 'fake-dida.json'), 'utf8'));
    changedAfterSubmission.alice.original.content = '滴答中的最新说明';
    changedAfterSubmission.bob[w.targetId].etag = 'changed-after-submission';
    await writeFile(path.join(dir, 'fake-dida.json'), JSON.stringify(changedAfterSubmission));
    response = await act('alice', 'approve'); assert.equal(response.status, 200); w = (await response.json()).workflow; assert.equal(w.status, 'done');
    const final = JSON.parse(await readFile(path.join(dir, 'fake-dida.json'), 'utf8')); assert.equal(final.alice.original.status, 2); assert.equal(final.bob[w.targetId].status, 2);
    assert.equal(final.alice.original.content, '滴答中的最新说明');
    assert.equal(final.bob[w.targetId].etag, 'changed-after-submission');
    // A public workflow completes without creating any publisher inbox task.
    await call('alice', '/api/room/tasks', { id: randomUUID(), action: 'create', fields: { title: '直接完成测试' } });
    const publicTask = (await (await call('bob')).json()).buffer[0];
    response = await call('bob', '/api/room/tasks', { id: randomUUID(), action: 'claim', source: { ownerId: null, taskId: publicTask.id, version: publicTask.version }, destination: 'bob' });
    const direct = (await response.json()).workflow;
    assert.equal(direct.reviewerTaskId, undefined);
    response = await call('alice', '/api/room/tasks', { id: randomUUID(), workflowId: direct.id, version: direct.version, action: 'owner-complete' }); assert.equal(response.status, 200);
    const completed = (await response.json()).workflow; assert.equal(completed.status, 'done'); assert.ok(completed.events.some(event => event.type === 'owner-complete'));
    const directlyDone = JSON.parse(await readFile(path.join(dir, 'fake-dida.json'), 'utf8')); assert.deepEqual(Object.keys(directlyDone.alice), ['original']); assert.equal(directlyDone.bob[direct.targetId].status, 2);
    await call('alice', '/api/room/tasks', { id: randomUUID(), action: 'create', fields: { title: '自己收取的任务' } });
    const personalPublic = (await (await call('alice')).json()).buffer.find(task => task.title === '自己收取的任务');
    const collect = { id: randomUUID(), action: 'claim', source: { ownerId: null, taskId: personalPublic.id, version: personalPublic.version }, destination: 'alice' };
    response = await call('alice', '/api/room/tasks', collect); const collected = await response.json(); assert.equal(response.status, 200); assert.equal(collected.operation.action, 'collect'); assert.equal(collected.operation.status, 'done'); assert.ok(!collected.workflow);
    assert.equal((await call('alice', '/api/room/tasks', collect)).status, 200);
    const afterCollection = await (await call('alice')).json(); assert.ok(!afterCollection.workflows.some(item => item.id === collect.id)); assert.ok(!afterCollection.buffer.some(item => item.id === personalPublic.id));
    const ordinary = afterCollection.members.find(member => member.id === 'alice').tasks.find(item => item.title === '自己收取的任务'); assert.ok(ordinary); assert.ok(!ordinary.workflowId); assert.ok(!ordinary.pending);
    response = await call('bob', '/api/room/tasks', { id: randomUUID(), action: 'claim', source: { ownerId: 'alice', taskId: ordinary.id, version: ordinary.version }, destination: 'bob' });
    assert.equal(response.status, 200); const laterClaim = (await response.json()).workflow; assert.equal(laterClaim.reviewerId, 'alice'); assert.equal(laterClaim.status, 'working');
    const deletion = { id: randomUUID(), workflowId: laterClaim.id, version: laterClaim.version, action: 'delete-claimed-task' };
    assert.equal((await call('alice', '/api/room/tasks', deletion)).status, 403);
    response = await call('bob', '/api/room/tasks', deletion); assert.equal(response.status, 200);
    assert.equal((await response.json()).workflow.status, 'deleted');
    assert.equal((await call('bob', '/api/room/tasks', deletion)).status, 200);
    const deletedSnapshot = await (await call('bob')).json();
    assert.ok(!deletedSnapshot.members.find(member => member.id === 'bob').tasks.some(task => task.id === laterClaim.targetId));
    assert.ok(!deletedSnapshot.members.find(member => member.id === 'alice').tasks.some(task => task.id === ordinary.id));
    const ownerDeletion = { id: randomUUID(), workflowId: w.id, version: w.version, action: 'delete-owner-task' };
    assert.equal((await call('bob', '/api/room/tasks', ownerDeletion)).status, 403);
    response = await call('alice', '/api/room/tasks', ownerDeletion); assert.equal(response.status, 200);
    assert.equal((await response.json()).workflow.status, 'deleted');
    assert.equal((await call('alice', '/api/room/tasks', ownerDeletion)).status, 200);
    const afterOwnerDeletion = JSON.parse(await readFile(path.join(dir, 'fake-dida.json'), 'utf8'));
    assert.ok(!afterOwnerDeletion.alice.original); assert.ok(!afterOwnerDeletion.bob[w.targetId]);
    assert.equal((await call('alice', file.url)).status, 200, 'submitted files remain accessible after deletion');

    await call('alice', '/api/room/tasks', { id: randomUUID(), action: 'create', fields: { title: '删除公共发起任务后继续审批' } });
    const removable = (await (await call('bob')).json()).buffer.find(task => task.title === '删除公共发起任务后继续审批');
    response = await call('bob', '/api/room/tasks', { id: randomUUID(), action: 'claim', source: { ownerId: null, taskId: removable.id, version: removable.version }, destination: 'bob' });
    w = (await response.json()).workflow;
    response = await act('bob', 'submit', { comment: '删除后保留的结果' }); w = (await response.json()).workflow;
    response = await act('alice', 'delete-owner-task'); assert.equal(response.status, 200); w = (await response.json()).workflow;
    assert.equal(w.status, 'deleted');
    assert.ok(!(await (await call('alice')).json()).buffer.some(task => task.id === removable.id));
    response = await act('alice', 'approve'); assert.equal(response.status, 409);
    assert.equal(w.events.find(event => event.type === 'submit').comment, '删除后保留的结果');
    await call('alice', '/api/room/tasks', { id: randomUUID(), action: 'create', fields: { title: '滴答失败也归档' } });
    const failedCard = (await (await call('bob')).json()).buffer.find(task => task.title === '滴答失败也归档');
    response = await call('bob', '/api/room/tasks', { id: randomUUID(), action: 'claim', source: { ownerId: null, taskId: failedCard.id, version: failedCard.version }, destination: 'bob' });
    const failedWorkflow = (await response.json()).workflow;
    const remoteFile = path.join(dir, 'fake-dida.json'), remoteState = JSON.parse(await readFile(remoteFile, 'utf8'));
    remoteState.bob[failedWorkflow.targetId].fixtureDeleteFailure = true;
    await writeFile(remoteFile, JSON.stringify(remoteState));
    const failedDeletion = { id: randomUUID(), workflowId: failedWorkflow.id, version: failedWorkflow.version, action: 'delete-owner-task' };
    response = await call('alice', '/api/room/tasks', failedDeletion);
    assert.equal(response.status, 200, 'website deletion is final even when Dida fails');
    const archived = (await response.json()).workflow;
    assert.equal(archived.status, 'deleted'); assert.equal(archived.error, '滴答清单中删除失败'); assert.equal(archived.ownerDeletePending, false);
    response = await call('alice', '/api/room/tasks', failedDeletion);
    assert.equal(response.status, 200); assert.equal((await response.json()).workflow.error, '滴答清单中删除失败');
    const archivedSnapshot = await (await call('bob', '/api/room/tasks?local=1')).json();
    assert.ok(!archivedSnapshot.buffer.some(task => task.id === failedCard.id));
    assert.equal(archivedSnapshot.workflows.find(item => item.id === archived.id).status, 'deleted');
    assert.equal(JSON.parse(await readFile(remoteFile, 'utf8')).bob[archived.targetId].deleteAttempts, 1);
    assert.equal(JSON.parse(await readFile(path.join(dir, 'room-collaboration.json'), 'utf8')).workflows[archived.id].ownerDeletion, undefined);
    assert.equal((await call('bob', '/api/room/tasks', { action: 'legacy-reset' })).status, 200);
  } finally { child.kill(); }
});
