import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { createHmac, randomUUID } from 'node:crypto';
import { createServer } from 'node:net';

test('room collaboration HTTP authenticates members, shares the buffer and rejects stale or foreign writes', { timeout: 30000 }, async () => {
  await mkdir('codex-generated/test-data', { recursive: true });
  const dir = await mkdtemp(path.resolve('codex-generated/test-data/cooperation-http-'));
  await writeFile(path.join(dir, 'identities.json'), JSON.stringify({ version: 1, users: { alice: { nickname: 'Alice' }, bob: { nickname: 'Bob' }, offline: { nickname: 'Offline' } } }));
  const legacyFile = path.join(dir, 'room-collaboration.json');
  await writeFile(legacyFile, JSON.stringify({ version: 1, revision: 0, buffer: {}, workflows: {}, operations: { obsolete: { action: 'move', status: 'pending' } }, legacyCleanup: [{ title: 'old warning' }], legacyReset: true }));
  const secret = randomUUID(), socket = createServer();
  await new Promise(resolve => socket.listen(0, '127.0.0.1', resolve));
  const port = socket.address().port;
  await new Promise(resolve => socket.close(resolve));
  const child = spawn(process.execPath, ['node_modules/next/dist/bin/next', 'start', '--hostname', '127.0.0.1', '--port', String(port)], { env: { ...process.env, DATA_DIR: dir, AUTH_SESSION_SECRET: secret, SITE_PASSWORD: 'fixture-login', IDENTITY_CODE_HASHES: '', VAPID_PUBLIC_KEY: '', VAPID_PRIVATE_KEY: '' }, stdio: 'ignore', windowsHide: true });
  const origin = `http://127.0.0.1:${port}`;
  const cookie = id => { const payload = `${id}.${Math.floor(Date.now() / 1000) + 600}`; return `ss_access=${payload}.${createHmac('sha256', secret).update(payload).digest('base64url')}`; };
  const call = (id, body, headers = {}) => fetch(`${origin}/api/room/tasks`, { method: body ? 'POST' : 'GET', redirect: 'manual', headers: { Cookie: cookie(id), Origin: origin, 'Content-Type': 'application/json', ...headers }, ...(body ? { body: JSON.stringify(body) } : {}) });
  try {
    let ready = false;
    for (let attempt = 0; attempt < 60; attempt++) {
      try { if ((await fetch(`${origin}/access`)).ok) { ready = true; break; } } catch {}
      await new Promise(resolve => setTimeout(resolve, 200));
    }
    assert.ok(ready);
    const diagnosticPath = '/api/ticktick/diagnostics';
    const loginPage = await (await fetch(`${origin}/access?next=${encodeURIComponent(diagnosticPath)}`)).text();
    assert.match(loginPage, /name="next" value="\/api\/ticktick\/diagnostics"/);
    const login = await fetch(`${origin}/api/access`, { method: 'POST', redirect: 'manual', body: new URLSearchParams({ identityCode: 'fixture-login', next: diagnosticPath }) });
    assert.equal(login.status, 303); assert.equal(login.headers.get('location'), diagnosticPath);
    const badLogin = await fetch(`${origin}/api/access`, { method: 'POST', redirect: 'manual', body: new URLSearchParams({ identityCode: 'wrong', next: diagnosticPath }) });
    assert.equal(new URL(badLogin.headers.get('location'), origin).searchParams.get('next'), diagnosticPath);
    const unlinkedDiagnostics = await fetch(`${origin}${diagnosticPath}`, { headers: { Cookie: cookie('alice') }, redirect: 'manual' });
    assert.equal(unlinkedDiagnostics.status, 401);
    assert.ok([307, 401].includes((await fetch(`${origin}/api/room/tasks`, { redirect: 'manual' })).status));
    assert.equal((await call('unknown')).status, 401);
    assert.ok(JSON.parse(await readFile(legacyFile, 'utf8')).operations.obsolete);
    assert.equal((await fetch(`${origin}/api/room/tasks?revision=1`, { headers: { Cookie: cookie('alice') } })).status, 200);
    let migrated;
    for (let attempt = 0; attempt < 50; attempt++) {
      migrated = JSON.parse(await readFile(legacyFile, 'utf8'));
      if (!migrated.operations.obsolete) break;
      await new Promise(resolve => setTimeout(resolve, 20));
    }
    assert.deepEqual(migrated.operations, {}); assert.ok(!('legacyCleanup' in migrated));
    const inspectPath = `${origin}/api/room/tasks?diagnose=${randomUUID()}`;
    assert.ok([307, 401].includes((await fetch(inspectPath, { redirect: 'manual' })).status));
    assert.equal((await fetch(inspectPath, { headers: { Cookie: cookie('unknown') }, redirect: 'manual' })).status, 401);
    assert.equal((await fetch(inspectPath, { headers: { Cookie: cookie('alice') } })).status, 404);
    assert.equal((await fetch(`${origin}/api/room/tasks?diagnose=invalid`, { headers: { Cookie: cookie('alice') } })).status, 400);
    const draftEndpoint = `${origin}/api/room/tasks/attachments?task=draft-test`;
    const stage = (actor = 'alice', headers = {}) => fetch(draftEndpoint, { method: 'POST', headers: { Cookie: cookie(actor), Origin: origin, 'X-File-Name': 'input.txt', ...headers }, body: 'preview text', redirect: 'manual' });
    assert.equal((await stage('alice', { Origin: 'https://foreign.example' })).status, 403);
    assert.equal((await stage('unknown')).status, 401);
    const pdfResponse = await stage('alice', { 'X-File-Name': 'preview.pdf' });
    const pdf = (await pdfResponse.json()).item;
    const pdfPreview = await fetch(`${origin}/api/room/tasks/attachments?path=${encodeURIComponent(pdf.path)}`, { headers: { Cookie: cookie('alice') } });
    assert.equal(pdfPreview.status, 200); assert.equal(pdfPreview.headers.get('content-type'), 'application/pdf');
    assert.match(pdfPreview.headers.get('content-disposition'), /^inline;/);
    assert.doesNotMatch(pdfPreview.headers.get('content-security-policy'), /sandbox/);
    const stagedResponse = await stage(); assert.equal(stagedResponse.status, 201);
    const draft = (await stagedResponse.json()).item;
    const previewUrl = `${origin}/api/room/tasks/attachments?path=${encodeURIComponent(draft.path)}`;
    const preview = await fetch(previewUrl, { headers: { Cookie: cookie('alice') } });
    assert.equal(preview.status, 200); assert.equal(await preview.text(), 'preview text');
    assert.match(preview.headers.get('content-type'), /text\/plain/);
    const range = await fetch(previewUrl, { headers: { Cookie: cookie('alice'), Range: 'bytes=0-6' } });
    assert.equal(range.status, 206); assert.equal(await range.text(), 'preview');
    assert.equal((await fetch(previewUrl, { headers: { Cookie: cookie('bob') } })).status, 404);
    const cloudDraft = `${origin}/api/cloud/files/${draft.path.split('/').map(encodeURIComponent).join('/')}`;
    assert.equal((await fetch(cloudDraft, { headers: { Cookie: cookie('alice') } })).status, 404);
    const draftContent = `[附件：input.txt](${origin}/task-attachment?path=${encodeURIComponent(draft.path)})`;
    assert.equal((await call('alice', { id: randomUUID(), action: 'create', fields: { title: '暂存生命周期测试', content: draftContent } })).status, 200);
    assert.equal((await fetch(cloudDraft, { headers: { Cookie: cookie('bob') } })).status, 200);
    const download = await fetch(previewUrl + '&download=1', { headers: { Cookie: cookie('bob') } });
    assert.equal(download.status, 200); assert.match(download.headers.get('content-disposition'), /^attachment;/);
    const savedDraft = (await (await call('alice')).json()).buffer[0];
    assert.equal((await call('alice', { id: randomUUID(), action: 'update', source: { ownerId: null, taskId: savedDraft.id, version: savedDraft.version }, fields: { content: '' } })).status, 200);
    assert.equal((await fetch(cloudDraft, { headers: { Cookie: cookie('alice') } })).status, 404);
    assert.equal((await fetch(previewUrl, { headers: { Cookie: cookie('alice') } })).status, 404, 'removed saved attachments cannot reappear from staging');
    const removedDraft = (await (await call('alice')).json()).buffer[0];
    await call('alice', { id: randomUUID(), action: 'delete', source: { ownerId: null, taskId: removedDraft.id, version: removedDraft.version } });
    const uploadUrl = `${origin}/api/cloud/files?path=tasks%2Ftest-task%2Funique`;
    const fileBody = Buffer.from('temporary attachment test');
    const upload = async (extra = {}) => fetch(uploadUrl, { method: 'POST', headers: { Cookie: cookie('alice'), Origin: origin, 'X-File-Name': encodeURIComponent('附件.txt'), ...extra }, body: fileBody, redirect: 'manual' });
    assert.equal((await upload({ Origin: 'https://foreign.example' })).status, 403);
    const uploaded = await upload(); assert.equal(uploaded.status, 201);
    const file = (await uploaded.json()).item;
    assert.equal(file.path, 'tasks/test-task/unique/附件.txt');
    const fileUrl = `/api/cloud/files/${file.path.split('/').map(encodeURIComponent).join('/')}`;
    const downloaded = await fetch(origin + fileUrl, { headers: { Cookie: cookie('bob') } });
    assert.equal(downloaded.status, 200); assert.equal(await downloaded.text(), fileBody.toString());
    assert.equal(downloaded.headers.get('cache-control'), 'private, no-store');
    const entry = `/task-attachment?path=${encodeURIComponent(file.path)}`;
    const guest = await fetch(origin + entry, { redirect: 'manual' });
    assert.equal(guest.status, 307); assert.equal(new URL(guest.headers.get('location'), origin).searchParams.get('next'), entry);
    const opened = await fetch(origin + entry, { headers: { Cookie: cookie('bob') }, redirect: 'manual' });
    assert.equal(opened.status, 307); assert.equal(opened.headers.get('location'), fileUrl);
    assert.equal((await fetch(`${origin}/task-attachment?path=tasks%2F..%2Fsecret`, { headers: { Cookie: cookie('alice') } })).status, 404);
    const oversized = await fetch(uploadUrl, { method: 'POST', headers: { Cookie: cookie('alice'), Origin: origin, 'X-File-Name': 'large.bin' }, body: Buffer.alloc(20 * 1024 * 1024 + 1) });
    assert.equal(oversized.status, 413);
    const attachmentContent = `说明\n\n[附件：附件.txt](${origin}${entry})`;
    const create = { id: randomUUID(), action: 'create', fields: { title: '全室共同任务', content: attachmentContent } };
    assert.equal((await call('alice', create, { Origin: 'https://foreign.example' })).status, 403);
    assert.equal((await call('alice', create)).status, 200);
    assert.equal((await call('alice', create)).status, 200);
    const result = await call('bob'), snapshot = await result.json();
    assert.equal(result.headers.get('cache-control'), 'private, no-store');
    assert.deepEqual(snapshot.members.map(member => member.id).sort(), ['alice', 'bob', 'legacy', 'offline']);
    assert.ok(snapshot.members.every(member => !member.connected));
    assert.equal(snapshot.buffer.length, 1);
    assert.equal(snapshot.buffer[0].content, attachmentContent);
    const task = snapshot.buffer[0], source = { ownerId: null, taskId: task.id, version: task.version };
    assert.equal((await call('bob', { id: randomUUID(), action: 'complete', source })).status, 403);
    assert.equal((await call('bob', { id: randomUUID(), action: 'update', source, fields: { title: '另一成员修改', priority: 5 } })).status, 200);
    assert.equal((await call('alice', { id: randomUUID(), action: 'delete', source })).status, 409);
    const next = (await (await call('alice')).json()).buffer[0];
    assert.equal(next.title, '另一成员修改');
    assert.equal((await call('alice', { id: randomUUID(), action: 'claim', source: { ...source, version: next.version }, destination: 'offline' })).status, 422);
    assert.equal((await call('alice', { id: randomUUID(), action: 'update', source: { ...source, version: next.version }, fields: { ticktickToken: 'injected' } })).status, 400);
    assert.equal((await call('bob', { id: randomUUID(), action: 'delete', source: { ...source, version: next.version } })).status, 200);
    assert.equal((await (await call('alice')).json()).buffer.length, 0);
  } finally { child.kill(); }
});
